### ISSUE TITLE
Integration tests not running due to change in Keboola access tokens

### ISSUE THREAD

**Issue by plmwong** [paybyphone/terraform-provider-keboola#41]
Keboola has changed their policy of issuing access tokens, so that tokens that 'users' create are time limited, and carry a different token prefix.

Since non-user access tokens do not have access to certain resources (e.g. they cannot manage access tokens themselves), those are not appropriate for running the integration tests as part of the travis-ci build.

Will need to figure out another solution or workaround. In the meantime, integration tests have been turned off by removing the setting `TF_ACC` from the defined environment variables of the travis-ci build.

**Comment by ujovlado** [comment]
Hey @plmwong, I was randomly checking issues and found this. :)

> Since non-user access tokens do not have access to certain resources (e.g. they cannot manage access tokens themselves), those are not appropriate for running the integration tests as part of the travis-ci build.

Few weeks ago we added option to create project token with "manage token permissions":
https://keboolamanagementapi.docs.apiary.io/#reference/projects/create-storage-token-in-project/create-storage-token

See option `canManageTokens`.

Hope it helps.

**Comment by plmwong** [comment]
Awesome, thanks! I'll try re-enabling these next week.

**Comment by plmwong** [comment]
Took me a while to find the https://connection.keboola.com/admin/account/access-tokens page for creating the 'Personal Access Token' that could be used in the `X-KBC-ManageApiToken` header, but once I got that, everything else was pretty straight-forward 👍 

Integration tests have been re-enabled, and have successfully run through in Travis CI for the `master` branch.
